package main

import (
	"fmt"
	"log"
	"net/http"
	"os"

	httpAdapter "calanggo-server/internal/adapters/http"
	"calanggo-server/internal/adapters/repository"
	"calanggo-server/internal/core/services"

	_ "calanggo-server/docs" // Docs generated by Swaggo

	httpSwagger "github.com/swaggo/http-swagger"
)

// @title           Calanggo URL Shortener API
// @version         1.0
// @description     API de alta performance para encurtamento de URLs em Go.

// @host            localhost:8080
// @BasePath        /
func main() {
	// 1. Adapters (Driven)
	// repo := repository.NewMemoryRepository()

	repo, err := repository.NewSQLiteRepository("calanggo.db")
	if err != nil {
		log.Fatalf("Falha ao inicializar banco de dados: %v", err)
	}

	// 2. Core (Service)
	service := services.NewLinkService(repo)
	handler := httpAdapter.NewLinkHandler(service)

	mux := http.NewServeMux()

	mux.HandleFunc("POST /api/v1/shorten", handler.CreateShortLink)
	mux.HandleFunc("GET /{code}", handler.Redirect)

	// Swagger
	mux.HandleFunc("GET /swagger/", httpSwagger.WrapHandler)

	// Redirect root to Swagger
	mux.HandleFunc("GET /", func(w http.ResponseWriter, r *http.Request) {
		http.Redirect(w, r, "/swagger/index.html", http.StatusFound)
	})

	port := os.Getenv("PORT")
	if port == "" {
		port = "8080"
	}

	serverAddr := ":" + port
	fmt.Printf("Calanggo Server iniciado na porta %s\n", port)
	fmt.Printf("Swagger UI disponível em http://localhost:%s/swagger/index.html\n", port)

	if err := http.ListenAndServe(serverAddr, mux); err != nil {
		log.Fatal(err)
	}
}
